### ISSUE TITLE
NEAT showing wrong inputs and connection count

### ISSUE THREAD

**Issue by winatawelly** [liquidcarrot/carrot#146] opened 2019-07-23 17:51 UTC
i tried running this script to testing out some basic model

        const dataset = [
            { input: [0,0], output: [0] },
            { input: [0,1], output: [1] },
            { input: [1,0], output: [1] },
            { input: [1,1], output: [0] }
        ];
       let Pops = new Neat(2,1);
       Pops.evaluate(dataset);
       let fittest = Pops.getFittest();
       console.log(fittest.toJSON());`

output

    {
      "nodes": [
        {
          "bias": 0,
          "type": "input",
          "squash": "LOGISTIC",
          "mask": 1,
          "index": 0
        },
        {
          "bias": 0.039815399456396255,
          "type": "output",
          "squash": "LOGISTIC",
          "mask": 1,
          "index": 1
        }
      ],
      "connections": [
        {
          "weight": 1.2941470809287727,
          "from": 0,
          "to": 1,
          "gater": null
        }
      ],
      "input": 1,
      "output": 1,
      "dropout": 0
    }`

however the json output showing that there's only one node and one connection,
do i missed something ???

**Comment by christianechevarria** [comment] 2019-07-23 19:43
Hey @winatawelly thanks for pointing this out. This is an interesting, but unexpected behavior -- I'll take a deeper look and get back to you on what might be going on

**Comment by winatawelly** [comment] 2019-07-24 03:58
> Hey @winatawelly thanks for pointing this out. This is an interesting, but unexpected behavior -- I'll take a deeper look and get back to you on what might be going on

Looking forward to it!

**Comment by luiscarbonell** [comment] 2019-07-24 08:55
@christianechevarria Any updates?

**Comment by winatawelly** [comment] 2019-07-24 14:17
> Hey @winatawelly thanks for pointing this out. This is an interesting, but unexpected behavior -- I'll take a deeper look and get back to you on what might be going on

Hi!,
Just letting you know that I just tried my earlier code on nodejs and it worked perfectly. didnt know what went wrong with the browser version.

**Comment by luiscarbonell** [comment] 2019-07-25 00:17
It looks like this is related to the webpack bundling script. 

Going to keep debugging a bit more.

**Comment by christianechevarria** [comment] 2019-08-11 12:56
Hey @winatawelly -- just wanted to give a heads up that we're reworking various parts of Neat to try and fix this bug 

Since this issue I've found some other bugs exclusive to the front-end, they all seem very similar so I suspect there's a common cause

**Comment by christianechevarria** [comment] 2019-08-12 02:32
Hey @winatawelly it seems like as of `v0.3.3` this bug is resolved:

https://codepen.io/christianechevarria/pen/pMxqEq?editors=0012 

Closing for now

**Closed by christianechevarria** 2019-08-12 02:32 UTC
Labels: 👀 high priority, 🕷️ bug
